### ISSUE TITLE
decode bytes to utf8 string for json.load()

### ISSUE THREAD

**Issue by wilocw** [lionfish0/download_thingspeak#1]
In ```download()```, lines 47 & 62, the line:

```
result = json.loads(requests.post(url).content)
```
Does not work for Python 3 < .6., with ```TypeError: the JSON object must be str, not 'bytes'```

Remedy by decoding to "utf-8"

```
result = json.loads(requests.post(url).content.decode('utf-8'))
```

**Comment by lionfish0** [comment]
Fixed in master.

**Comment by wilocw** [comment]
thank u for your prompt response.
